language: r
cache: packages

r_packages:
  - cwbtools
  - RCurl
  - curl
  - polmineR
  - covr
  - rmarkdown

r_github_packages:
  - r-lib/covr

warnings_are_errors: false

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov(type = "all", token = "50a5deef-1941-43d6-93e3-a1b7e6d31aad")'
